name: Auto Release

on:
  schedule:
    - cron: "0 6 1 * *" # 1st of month, 06:00 UTC
  workflow_dispatch:

jobs:
  release:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-auto-release.yaml@5854d1379b5f178ecda8199576cbc5a937675427 # main
    secrets: inherit
