name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (e.g. v0.1.0)"
        required: true

jobs:
  image:
    permissions:
      contents: read
      packages: write
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-release.yaml@b8b78875cfbab500771a9546fcc361f5630a32fc # main
    with:
      tag: ${{ github.event.inputs.tag || '' }}
